### ISSUE TITLE
PKGBUILD improvements

### ISSUE THREAD

**Issue by xiota** [hrehfeld/archlinux-whisper.cpp-model#2]
I would like to combine `whisper.cpp-model-*` into a single split package.  This is possible without downloading all the source files by using environment variables to control the build.  Here is an example: [`spleeter-data`](https://aur.archlinux.org/pkgbase/spleeter-data)

I would also like to improve the description and fix the license string.

**Comment by hrehfeld** [comment]
As the scripting work is already done, I prefer this solution (for the users). It's much easier to just install a package for the specific size than figuring out build instructions for this specific PKGBUILD, isn't it?

What do you think?

**Comment by hrehfeld** [comment]
Closing as no feedback. Feel free to comment still.
