### ISSUE TITLE
New pkgver method generate constant update warnings

### ISSUE THREAD

**Issue by Marzal** [hrehfeld/archlinux-whisper.cpp-model#6]
Hi. With the new download method I constantly get and update warning:

```
aur/whisper.cpp-model-large-v3-q5_0  a551933542d956ae84634937acd2942eb40efaaf-1 -> 2-1
aur/whisper.cpp-model-medium         a551933542d956ae84634937acd2942eb40efaaf-1 -> 2-1
```

because the ***pkgver*** once installed is this:

    pkgver() {
      git ls-remote "$_baseurl" master | cut -f 1 | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
    }

https://aur.archlinux.org/packages/whisper.cpp-model-large-v3-q5_0#comment-990491

https://aur.archlinux.org/cgit/aur.git/commit/?h=whisper.cpp-model-large-v3-q5_0&id=da8a8312e21b6f5b604749ac73798cdef42864af

PD: Thanks for your work.

**Comment by hrehfeld** [comment]
I changed the versioning back to my own version numbers instead of git-based. Hope it works out now.

**Comment by Marzal** [comment]
> I changed the versioning back to my own version numbers instead of git-based. Hope it works out now.

Hi, I think you resolved the problem with the last commit,
https://aur.archlinux.org/cgit/aur.git/commit/?h=whisper.cpp-model-large-v3-q5_0&id=4b1d9acfc9470d56a63fccc2a6590127bcaaf550
https://github.com/hrehfeld/archlinux-whisper.cpp-model/commit/04e1c0baf793ed8ccca5423767f6ca1aa3ab35c2
but in AUR we need a bump in the `pkgrel` in order to apply.

Thanks for your time, deeply appreciated.
