### ISSUE TITLE
error: packages failed to build: whisper.cpp-model-medium-2-1

### ISSUE THREAD

**Issue by homocomputeris** [hrehfeld/archlinux-whisper.cpp-model#7]
Downloading download-ggml-model-fdbfb460ed546452a5d53611bba66d10d842e719.sh...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3073  100  3073    0     0   4725      0 --:--:-- --:--:-- --:--:--  4725
==> Validating source files with sha256sums...
    download-ggml-model-fdbfb460ed546452a5d53611bba66d10d842e719.sh ... FAILED
==> ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'whisper.cpp-model-medium-2-1': 
error: packages failed to build: whisper.cpp-model-medium-2-1

**Comment by hrehfeld** [comment]
This should now be fixed.
